### ISSUE TITLE
OtherGames Not working with ue5.1.1

### ISSUE THREAD

**Issue by THW-Reaper** [djhaled/Uiana-MapImporter#9]
What Engine versions does it support? What would I have to modify to make it compatible with ue5.1.1?

**Comment by djhaled** [comment]
OtherGames is not actively supported.

I still have a project for a universal map extractor for unreal, soon in the future i'll be working on it.

**Comment by THW-Reaper** [comment]
> I still have a project for a universal map extractor for unreal, soon in the future i'll be working on it.

Hope I'm not a bother, what's the status on that universal map importer? Side note: I noticed Gmatrix's "Json to asset" plug-in, which looks promising for making the proper mats/instances. Just a thought.

**Comment by KaiserM21** [comment]
> 
> > I still have a project for a universal map extractor for unreal, soon in the future i'll be working on it.
> 
> Hope I'm not a bother, what's the status on that universal map importer? Side note: I noticed Gmatrix's "Json to asset" plug-in, which looks promising for making the proper mats/instances. Just a thought.

JsonAsAsset only works because Fortnite with UEFN has editor-only data that can be used for constructing materials, it will not work with a regular game. 
Idk if bK has something in the works, but I'm doing some tests with a C# based universal map importer using socket import(Blender/Unreal). No date or anything, currently figuring out custom model format for it, u can check progress on my repo.

**Comment by THW-Reaper** [comment]
Will do, thanks Zain!
